apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: my-workflow
  namespace: argo
spec:
  arguments:
    parameters:
      - name: org
        value: "StasikLeyshin"
      - name: repo
        value: "gateway"
      - name: k8repo
        value: "gateway"
      - name: branch
        value: "master"
      - name: branch1
        value: "deploy"

      - name: repo-deployment
        value: "deployment"
      - name: branch-deployment
        value: "main"
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: git-clone
            template: git-clone
            arguments:
              parameters:
                - name: repo
                  value: "https://github.com/{{workflow.parameters.org}}/{{workflow.parameters.repo}}.git"
        - - name: docker-build
            template: build
            arguments:
              artifacts:
                - name: repo
                  from: "{{steps.git-clone.outputs.artifacts.repo}}"
              parameters:
                - name: image
                  value: "{{steps.git-clone.outputs.parameters.generated-image-tag}}"
        - - name: git-push
            template: update
            arguments:
              parameters:
                - name: repo-deployment
                  value: "git@github.com:{{workflow.parameters.org}}/{{workflow.parameters.repo-deployment}}.git"
                - name: imageID
                  value: "{{steps.git-clone.outputs.parameters.generated-image-tag}}"
                - name: branch-deployment
                  value: "{{workflow.parameters.branch-deployment}}"
              artifacts:
                - name: repo
                  from: "{{steps.git-clone.outputs.artifacts.repo}}"

#        - - name: git-clone-deployment
#            template: git-clone-deployment
#            arguments:
#              parameters:
#                - name: repo-deployment
#                  value: "https://github.com/{{workflow.parameters.org}}/{{workflow.parameters.repo-deployment}}.git"
#        - - name: build-push-helm
#            template: build-helm
#            arguments:
#              artifacts:
#                - name: repo-deployment
#                  from: "{{steps.git-clone-deployment.outputs.artifacts.repo-deployment}}"
#              parameters:
#                - name: image-deployment
#                  value: "{{steps.git-clone-deployment.outputs.parameters.generated-image-tag-deployment}}"
    - name: get-branch
      outputs:
        parameters:
          - name: generated-branch-tag
            valueFrom:
              path: /tmp/branch_tag
      container:
        image: alpine/git:2.36.3
        workingDir: /repo
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            branch={{workflow.parameters.branch}} && echo $branch | cut -d'/' -f3-  > /tmp/branch_tag
    - name: git-clone
      inputs:
        parameters:
          - name: repo
        artifacts:
          - name: repo
            path: /repo
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{workflow.parameters.branch}}"
      volumes:
        - name: docker-config
          configMap:
            name: docker-config
      container:
        image: golang:1.10
        command: [sh, -c]
        args: ["echo \"$(basename -s .git $(git config --get remote.origin.url) | sed -r 's/[/_]/-/g'):$(git rev-parse | sed -r 's/[/_]/-/g')$(git describe --tags)\" > /tmp/image_tag"]
        workingDir: /repo
      outputs:
        artifacts:
          - name: repo
            path: /repo/
            s3:
              insecure: true
              endpoint: 192.168.1.41:31217
              bucket: argo
              region: us-west-2
              key: path/git/repo.tgz

              accessKeySecret:
                name: my-s3-credentials
                key: accessKey
              secretKeySecret:
                name: my-s3-credentials
                key: secretKey
        parameters:
          - name: generated-image-tag
            valueFrom:
              default: "default"
              path: /tmp/image_tag
    - name: build
      inputs:
        artifacts:
          - name: repo
            path: repo
        parameters:
          - name: image
      container:
        image: gcr.io/kaniko-project/executor:v1.23.2
        workingDir: /repo
        command: [/kaniko/executor]
        args:
          - --dockerfile=Dockerfile
          #- --build-arg=GITHUB_TOKEN=$(GIT_ACCESS_TOKEN)
          - --destination=192.168.1.41/{{inputs.parameters.image}}
          - --cache=true
          - --compressed-caching=false
          #- --cache-repo=asia-south1-docker.pkg.dev/project-id/repo-name/{{workflow.parameters.repo}}-cache
          - --context=/repo
          - --insecure
    - name: update
      inputs:
        parameters:
          - name: imageID
          - name: repo-deployment
          - name: branch-deployment
        artifacts:
          - name: repo1
            path: /repo
            git:
              repo: "{{inputs.parameters.repo-deployment}}"
              revision: "{{inputs.parameters.branch-deployment}}"
              sshPrivateKeySecret:
                name: github-credentials
                key: ssh-privatekey
              depth: 1
      container:
        image: alpine/git:2.36.3
        workingDir: /repo
        command:  ["/bin/sh"]
        args:
          - -c
          - >-
            set -x &&
            ls &&
            Image_ID={{inputs.parameters.imageID}} &&
            Image_ID=${Image_ID#*:} &&
            echo $Image_ID &&
            git checkout {{inputs.parameters.branch-deployment}} &&
            cd {{workflow.parameters.repo}} &&
            sed -i "s/:v.*/:$Image_ID/g" values.yaml &&
            cat values.yaml &&
            git status &&
            git branch &&
            git config --global user.email "vladtit81@gmail.com" &&
            git config --global user.name {{workflow.parameters.org}} &&
            git remote set-url origin https://$GIT_ACCESS_TOKEN@github.com/{{workflow.parameters.org}}/{{workflow.parameters.repo-deployment}}.git &&
            git add values.yaml &&
            git commit -m "Automation updated values.yaml" &&
            git push --set-upstream origin {{inputs.parameters.branch-deployment}}
        env:
          - name: GIT_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitaccesstoken
                key: ghtoken


#    - name: git-clone-deployment
#      inputs:
#        parameters:
#          - name: repo-deployment
#        artifacts:
#          - name: repo-deployment
#            path: /repo-deployment
#            git:
#              repo: "{{inputs.parameters.repo-deployment}}"
#              revision: "{{workflow.parameters.branch-deployment}}"
#      container:
#        image: golang:1.10
#        command: [ sh, -c ]
#        args: [ "echo \"$(git rev-parse | sed -r 's/[/_]/-/g')$(git describe --tags)\" > /tmp/image_tag_deployment" ]
#        workingDir: /repo-deployment
#      outputs:
#        artifacts:
#          - name: repo-deployment
#            path: /repo-deployment/
#            s3:
#              insecure: true
#              endpoint: 192.168.1.41:31217
#              bucket: argo
#              region: us-west-2
#              key: path/git/repo-deployment.tgz
#
#              accessKeySecret:
#                name: my-s3-credentials
#                key: accessKey
#              secretKeySecret:
#                name: my-s3-credentials
#                key: secretKey
#        parameters:
#          - name: generated-image-tag-deployment
#            valueFrom:
#              default: "default"
#              path: /tmp/image_tag_deployment
#
#    - name: build-helm
#      inputs:
#        artifacts:
#          - name: repo-deployment
#            path: repo-deployment
#        parameters:
#          - name: image-deployment
#      container:
#        image: alpine/helm:3.16
#        workingDir: /repo-deployment
#        command:  ["/bin/sh"]
#        args:
#          - -c
#          - >-
#            helm repo add chartmuseum http://192.168.1.41:31744 &&
#            helm package library-chart -d library-chart/ --version {{inputs.parameters.image-deployment}} &&
#            cd library-chart &&
#            ls &&
#            curl -v --data-binary "@library-{{inputs.parameters.image-deployment}}.tgz"  http://192.168.1.41:31744/api/charts
