apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      repositories:
        - owner: StasikLeyshin
          names:
            - gateway
      webhook:
        endpoint: /webhook
        port: "12000"
        method: POST
      events:
        - "*"
      webhookSecret:
        name: webhook-token
        key: my-token
      insecure: false
      active: true
      contentType: "json"


---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-token
type: Opaque
stringData:
  my-token: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: webhook-token
spec:
  restartPolicy: OnFailure
  volumes:
    - name: webhook-token
      secret:
        secretName: webhook-token
  containers:
    - name: webhook-token-test
      image: registry.k8s.io/busybox
      command:
        - ls
        - "-l"
        - "/etc/secret-volume-webhook-token"
      volumeMounts:
        - name: webhook-token
          readOnly: true
          mountPath: "/etc/secret-volume-webhook-token"
