apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-deployment
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-docker-publish-workflow-dependency-stag
      eventSourceName: webhook-deployment
      eventName: example
  triggers:
    - template:
      #conditions: "github-docker-publish-workflow-dependency-stag"
        name: my-workflow-deployment
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: my-workflow-deployment-
                namespace: argo
              spec:
#                archiveLogs: true
#                activeDeadlineSeconds: 3600
#                ttlStrategy:
#                  secondsAfterCompletion: 259200 # 3 days
#                arguments:
#                  parameters:
#                    - name: org
#                    - name: repo-deployment
                workflowTemplateRef:
                  name: my-workflow-deployment
#          parameters:
#            - src:
#                dependencyName: github-docker-publish-workflow-dependency-stag
#                dataKey: body.repository.owner.name
#              dest: spec.arguments.parameters.0.value
#            - src:
#                dependencyName: github-docker-publish-workflow-dependency-stag
#                dataKey: body.repository.name
#              dest: spec.arguments.parameters.1.value

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-workflow-
  namespace: argo
spec:
  workflowTemplateRef:
    name: my-workflow
