grpc:
  host: "localhost"
  port: 5005

grpc_gateway:
  port: 5001

route:
  node_id: "1111"
  server_manager_address: "localhost:8181"

mongo:
  connection_string: "mongodb://mongo-service:27017"
  database_name: "gateway"