name: k3s Testing
on:
  push:
    branches:
      - 'fix/**'
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods